# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: "57B62W4326",
      issuer_id: "2475be71-6f9d-4231-8933-e9ecfe0eacd8",
      key_content: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKXMYpdXjUq008Ia252ui7QSjH8asoW1Uq63dnVzJvYegCgYIKoZIzj0DAQehRANCAAQywbncaisjVXxmetTqwZhh7xjqNNB4uVJjYJ7SP6qc/2h7LMUcLnzxXsW5G9sgAWw8+dOuHrrBxMxgq1gTswyK\n-----END PRIVATE KEY-----",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    sync_code_signing(type: "appstore")    # see code signing guide for more information
    increment_build_number(xcodeproj: "MyApp.xcodeproj")
    build_app(
      workspace: "MyApp.xcworkspace", 
      scheme: "MyApp",
      output_directory: "./fastlane" # Destination directory. Defaults to current directory.
    )
    upload_to_testflight(
      ipa: "./fastlane/MyApp.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
